#!/bin/bash

# Sane error handling
# See <https://stackoverflow.com/a/821419/15920018>
set -Eeuo pipefail

echo "Releasing Orion v$1..."


# Move jj bookmarks
jj bookmark set dev main -r @-

# Push to git
git switch dev && git push
git switch main && git push


### MDN release ###
echo "Starting MDN release..."
web-ext sign --api-key=$MDN_AMO_API_KEY --api-secret=$MDN_AMO_API_SECRET --channel=unlisted


### Chrome release ###
echo "Starting Chrome release..."

# Copy everything to temp dir
rm -rf ~/Desktop/orion
cp -r ./ ~/Desktop/orion
echo "Copied files to ~/Desktop/orion"

# Remove unwanted files/dirs
rm -rf ~/Desktop/orion/.git
rm -rf ~/Desktop/orion/.jj
rm -rf ~/Desktop/orion/web-ext-artifacts
rm ~/Desktop/orion/.amo-upload-uuid
rm ~/Desktop/orion/publish-release
echo "Removed git, jj, and amo files/dirs."

# zip it
# See ditto man page (this is very similar to Finder compress function)
ditto -c -k --sequesterRsrc --keepParent ~/Desktop/orion ~/Desktop/orion.zip
rm -rf ~/Desktop/orion
echo "Zipped into ~/Desktop/orion.zip"


### Github release ###
echo "Starting Github release"
gh release create "v$1" --generate-notes -F ./CHANGELOG.md

# Upload files
cp "./web-ext-artifacts/65a14653bc7c4e6ab617-$1.xpi" ~/Desktop/65a14653bc7c4e6ab617.xpi
gh release upload "v$1" ~/Desktop/65a14653bc7c4e6ab617.xpi
gh release upload "v$1" ~/Desktop/orion.zip

# Clean up
rm ~/Desktop/65a14653bc7c4e6ab617.xpi
# Don't remove, because it needs to be uploaded manually.
# rm ~/Desktop/orion.zip
open ~/Desktop
